name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      uses: uraimo/run-on-arch-action@v2
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu_latest
        run: docker build . --file Dockerfile --tag toddpratt/portfolio:1.$GITHUB_RUN_NUMBER
  
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: toddpratt
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: docker push toddpratt/portfolio:1.$GITHUB_RUN_NUMBER
